[package]
name = "egui-wine-test"
version = "0.1.0"
edition = "2021"

[dependencies]
baseview = { git = "https://github.com/RustAudio/baseview.git", features = ["opengl"] }
gl = "0.14"

[features]
default = ["opengl"]
opengl = []
